@echo off
rfsaextract.exe STREAMS_IN\ADVERTS STREAMS_IN\CH STREAMS_IN\CO STREAMS_IN\CR STREAMS_IN\DS STREAMS_IN\HC STREAMS_IN\MH STREAMS_IN\MR STREAMS_IN\NJ STREAMS_IN\RE STREAMS_IN\RG STREAMS_IN\TK STREAMS metadata-win32.conf
