adverts = {
    "American Bank of Los Santos.ogg":                                   61.997,
    "Ammunation.ogg":                                                    60.129,
    "Beagle Brokerage and Pawn.ogg":                                     47.916,
    "Blotto's #1.ogg":                                                   31.629,
    "Blotto's #2.ogg":                                                   20.103,
    "Blotto's #3.ogg":                                                   24.119,
    "Bouche Cologne.ogg":                                                25.745,
    "Casa City.ogg":                                                     38.955,
    "Castradon.ogg":                                                     77.757,
    "Celebrate with cake #1.ogg":                                        30.996,
    "Celebrate with cake #2.ogg":                                        26.630,
    "Change your identity.ogg":                                          61.360,
    "Cluckin' Bell #1.ogg":                                              48.645,
    "Cluckin' Bell #2.ogg":                                              48.000,
    "Commando Pest Eradication.ogg":                                     75.827,
    "Commemorative Miniatures.ogg":                                      84.283,
    "Creative plastic surgery.ogg":                                      74.418,
    "Crimson Executive Spouse Indemnity Services.ogg":                   63.444,
    "de Koch Diamonds.ogg":                                              46.841,
    "Don't Let Your Children Ride Bicycles.ogg":                         75.605,
    "Dream makers.ogg":                                                  73.935,
    "Eris Shoes.ogg":                                                    78.226,
    "Executive Intruder Extermination Service.ogg":                      61.513,
    "Exorbio Gaming System.ogg":                                         54.272,
    "Fokari Film.ogg":                                                   42.805,
    "Grin.ogg":                                                          67.872,
    "Hampshire Nannies Ltd..ogg":                                        73.956,
    "Herr Gruber's spa.ogg":                                             50.966,
    "Intergalactic Wrestling Championship on Weasel TV.ogg":             81.224,
    "Inversion Therapy.ogg":                                             59.876,
    "Kilimanjaro clothes #1.ogg":                                        49.898,
    "Kilimanjaro clothes #2.ogg":                                        61.025,
    "Lager Beer.ogg":                                                    31.605,
    "Lager Light.ogg":                                                   49.163,
    "Law on Weasel #1.ogg":                                              22.293,
    "Law on Weasel #2.ogg":                                              22.270,
    "Law on Weasel #3.ogg":                                              24.779,
    "Lustrious #1.ogg":                                                  59.415,
    "Lustrious #2.ogg":                                                  48.019,
    "Mike Andrews #1.ogg":                                               51.029,
    "Mike Andrews #2.ogg":                                               55.180,
    "My Five Uncles on LSBC.ogg":                                        56.548,
    "Proposition 421 (smoking ban).ogg":                                 39.966,
    "Proposition 602 (driving on bus lanes).ogg":                        40.163,
    "Proposition 832 (green cards for illegal aliens":                   43.974,
    "Rapidite.ogg":                                                      48.498,
    "Redwood Cigarettes.ogg":                                            50.069,
    "Renegade Cologne.ogg":                                              47.709,
    "San Andreas Telephones #1.ogg":                                     16.432,
    "San Andreas Telephones #2.ogg":                                     23.748,
    "San Andreas Telephones #3.ogg":                                     21.422,
    "San Andreas Telephones #4.ogg":                                     19.936,
    "Shine by Helmet Shine.ogg":                                         43.062,
    "Sooth.ogg":                                                         55.522,
    "Sprunk.ogg":                                                        47.085,
    "Starfish Resort and Casino.ogg":                                    64.123,
    "The Cavern of Sorrow.ogg":                                          65.328,
    "The Crazy Cup.ogg":                                                 85.732,
    "The Epsilon Program #1.ogg":                                        46.608,
    "The Epsilon Program #2.ogg":                                        35.504,
    "The Epsilon Program #3.ogg":                                        42.235,
    "The Glory Hole Theme Park #1.ogg":                                  49.736,
    "The Glory Hole Theme Park #2.ogg":                                  48.896,
    "The Midlife Crisis Center.ogg":                                     70.125,
    "The Military.ogg":                                                  72.731,
    "Tropicarcinoma.ogg":                                                62.285,
    "Ultimate Disc in the Dark.ogg":                                     65.853,
    "Zebra Bar #1.ogg":                                                  31.649,
    "Zebra Bar #2.ogg":                                                  30.537,
}
